//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dreambook
{
    using System;
    using System.Collections.Generic;
    
    public partial class DreamList
    {
        public int idDream { get; set; }
        public string Name { get; set; }
        public string Target { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public System.DateTime DateExpired { get; set; }
        public int Splitphase { get; set; }
        public string Status { get; set; }
    }
}
